title: "Risorse Artificiali"
timezone: "Europe/Rome"
email: maestri.stefano@gmail.com
description: >-
  Risorse Artificiali è la tua bussola settimanale nel mondo dell’Intelligenza Artificiale Generativa. Notizie, tendenze, strumenti e riflessioni critiche.
baseurl: "" 
url: "https://risorseartificiali.com"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache

author:
  name: "Risorse Artificiali"
  avatar: "/assets/images/profile.jpg"
  bio: "La tua bussola settimanale <br/> nel mondo dell’AI"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/company/risorseartificiali/"
    - label: "X / Twitter"
      icon: "fab fa-twitter"
      url: "https://x.com/risorseAI"
    - label: "YouTube"
      icon: "fab fa-youtube"
      url: "https://www.youtube.com/channel/UCYQgzIby7QHkXBonTWk-2Fg"
    - label: "Spotify"
      icon: "fab fa-spotify"
      url: "https://open.spotify.com/show/16dTKEEtKkIzhr1JJNMmSF?si=900902f2dca8442e"
    - label: "Apple Podcasts"
      icon: "fab fa-apple"
      url: "https://podcasts.apple.com/us/podcast/risorse-artificiali-appunti-e-spunti-dal-mondo-dellintelligenza/id1816213074"
    - label: "Amazon Music"
      icon: "fab fa-amazon"
      url: "https://music.amazon.it/podcasts/d483b182-41a7-4b03-ba9c-a75e528ea7ed/risorse-artificiali-appunti-e-spunti-dal-mondo-dell%E2%80%99intelligenza-artificiale"

# Abilita sezione autore nella homepage
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
      share: true   # Abilita i tasti di condivisione social sotto gli articoli
      comments: true # Predispone per i commenti (se li userai)

collections:
  pages:
    output: true
    permalink: /:path/
